#!/bin/bash
set -euxo pipefail

echo "Running track setup script"

# Wait for the Instruqt host bootstrap to finish.
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Here we are installing the nginx package. The noninteractive setting ensures
# that the apt command won't stop and ask for user input.
apt -y update
DEBIAN_FRONTEND=noninteractive apt -y install nginx

# Remove the default nginx landing page and replace
# it with something more useful.
rm /var/www/html/index.nginx-debian.html
cat >> /var/www/html/index.html <<-EOF
<html>
  <head><title>Meow!</title></head>
  <body>
  <div style="width:800px;margin: 0 auto">
  <!-- BEGIN -->
  <center><img src="http://placekitten.com/640/480"></img></center>
  <center><h2>Meow World!</h2></center>
  <center>Welcome to the Meow World application. Meow! =^._.^=</center>
  <!-- END -->
  </div>
  </body>
</html>
EOF

# Start up the nginx service.
service nginx start


### Install Java
apt update -y
apt install openjdk-11-jdk -y
java -version 

####### Install Jenkins

curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
  /usr/share/keyrings/jenkins-keyring.asc > /dev/null
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null
apt-get update -y 
apt-get install jenkins -y

####### Install Git 
sudo useradd -s /bin/bash -d /home/git/ -m -G sudo git
sudo mkdir /home/git/.ssh/
sudo chmod 0700 /home/git/.ssh/
KEY=$(cat ~/.ssh/id_rsa.pub)
echo "$KEY"
sudo -- sh -c "echo '$KEY' > /home/git/.ssh/authorized_keys"
sudo chown -R git:git /home/git/.ssh/
sudo mkdir /home/git/project.git
sudo chmod 0700 /home/git/project.git/
sudo -- sh -c "cd /home/git/project.git ; git init --bare"
sudo chown -R git:git  /home/git/project.git/



